### PR TITLE
LPS-67418 Tests

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary @robertoDiaz

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/com-liferay-adaptive-media/pull/7. [See changes here.](https://github.com/adolfopa/com-liferay-adaptive-media/compare/28a3171~5...28a3171) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/com-liferay-adaptive-media/pull/4. [See changes here.](https://github.com/adolfopa/com-liferay-adaptive-media/compare/6172a27~6...6172a27) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
